//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_staj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKcomEntities : DbContext
    {
        public BKcomEntities()
            : base("name=BKcomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblDosya> tblDosya { get; set; }
        public virtual DbSet<tblOgretmen> tblOgretmen { get; set; }
        public virtual DbSet<tblStajerler> tblStajerler { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
    }
}
